// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package sqldemo1;

@net.sf.jni4net.attributes.ClrType
public class SQLConnect1 extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected SQLConnect1(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public SQLConnect1() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        sqldemo1.SQLConnect1.__ctorSQLConnect10(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorSQLConnect10(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;)V")
    public native static void conn_details(java.lang.String DB_Name, java.lang.String Table_Name);
    
    public static system.Type typeof() {
        return sqldemo1.SQLConnect1.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        sqldemo1.SQLConnect1.staticType = staticType;
    }
    //</generated-proxy>
}
